name: actionlint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    uses: thadiust/workflow-python/.github/workflows/reusable-actionlint.yml@v1.0.8
